kind: pipeline
type: docker
name: default

steps:
- name: show_env
  image: adhanali/blue42
  commands:
  - echo "foo: ${foo}"
  - env

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: adhanali/blue42
  commands:
  - mkdir -p _build
  - cd _build
  - cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-gcc-toolchain.cmake
  - cmake --build .
  - cp /opt/nordic/nRF5_SDK_16.0.0/components/softdevice/s140/hex/s140_nrf52_7.0.1_softdevice.hex .
