kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/lagerdata/blue42.git /app --recurse-submodules

- name: build
  image: adhanali/blue42
  commands:
  - cd /app
  - mkdir -p _build
  - cd _build
  - cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE=../cmake/arm-gcc-toolchain.cmake
  - cmake --build .
